apiVersion: apps/v1
kind: Deployment
metadata:
  name: teleport-agent
  namespace: teleport
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teleport-agent
  template:
    metadata:
      labels:
        app: teleport-agent
    spec:
      containers:
        - name: teleport-agent
          image: public.ecr.aws/gravitational/teleport:16.4.12
          command:
            - teleport
            - start
            - --roles=node
            - --token=teleporttoken123
            - --auth-server=teleport-auth.teleport.svc.cluster.local:3025
