- name: Setup Teleport on the VM
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      apt:
        name: [curl, tar]
        update_cache: yes

    - name: Download and install Teleport
      shell: |
        curl -LO https://cdn.teleport.dev/teleport-v16.4.12-linux-amd64-bin.tar.gz
        tar -xzf teleport-v16.4.12-linux-amd64-bin.tar.gz
        cd teleport && install teleport tctl tsh /usr/local/bin/
      args:
        executable: /bin/bash

    - name: Generate minimal Teleport config
      copy:
        dest: /etc/teleport.yaml
        content: |
          teleport:
            nodename: teleport-vm
            data_dir: /var/lib/teleport
            log:
              output: stderr
              severity: INFO
          auth_service:
            enabled: true
          ssh_service:
            enabled: true
          proxy_service:
            enabled: true
